server:
  port: 8080

spring:
  application:
    name: RedisTest

  redis:
    host: 127.0.0.1
    password:      #因为我本地redis没有设置密码，所以这里也不设置密码
    database: 0
    port: 6379
    connect-timeout: 10000ms    #连接超时时间
    lettuce:
      pool:
        max-active: 8      #最大连接数量
        max-idle: 8       #最大空闲连接
        max-wait: -1ms       #最大阻塞等待时间（使用负值表示无限制）
        min-idle: 0       #最小空闲连接
